---

# obtained from
# https://github.com/anmol098/waka-readme-stats#profile-repository

name: Waka Readme

on:
  schedule:
    # Runs every day at midnight
    # https://crontab.guru/every-day-at-midnight
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Waka Metrics in Readme
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # https://github.com/anmol098/waka-readme-stats#flags-available
          COMMIT_MESSAGE: "docs(readme): update wakatime stats"
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%Y/%m/%d %H:%M:%S"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TIMEZONE: "False"
          SHOW_PROFILE_VIEWS: "False"
